#!/usr/bin/env bash
# bash script to transfer file from local to remote servers

if [[ $# -lt 3 ]] || [[ $# -gt 4 ]] ;
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
elif [[ $# -eq 3 ]];
then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
elif [[ $# -eq 4 ]];
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi

