#!/usr/bin/env bash
# bash script to transfer file from local to remote server

path_local="$1"
server_ip="$2"
user_name="$3"
path_ssh_key="$4"

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -i "$path_ssh_key" "$path_local" "$user_name"@"$server_ip":~/


