#!/usr/bin/env bash
# Install nginx web server on my server

apt-get update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default


sudo service nginx start

