#!/usr/bin/env bash
# configute error_page directive on nginx

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sed -i -e "/server_name _;/ {
        N
        s/server_name _;/server_name _;\\n\\n\
\\tlocation \\/redirect_me {\\n\
\\t\\treturn 301 https:\\/\\/www.youtube.com\\/watch?v=QH2-TGUlwu4;\\n\
\\t}\\n\
\\terror_page 404 \\/custom_404.html;/
        p
        x
}" /etc/nginx/sites-enabled/default

service nginx start
