#!/usr/bin/env bash
# bash script to automate the configuration

sudo apt-get update
sudo apt-get -y install nginx

header="add_header X-Served-By $(hostname);"

if ! grep -q 'X-Served-By' '/etc/nginx/sites-available/default'; then
        sudo sed -i "37i $header" /etc/nginx/sites-available/default
fi

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i "28i\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

sudo sed -i "31i\ error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
