#!/usr/bin/env bash
# MySQL backup

date=$(date +%d-%m-%Y)
archive_file="${date}.tar.gz"

sudo mysqldump -u root -p"$1" --all-databases > backup.sql
if [[ -e backup.sql ]]; then
	sudo tar czf "${archive_file}" backup.sql
fi




