#!/usr/bin/env bash
# Check if argument is provided

if [ $# -ne 1 ]; then
    name=$(echo $0 | cut -d'/' -f2-)
    echo "Usage: $name  {IP_ADDRESS}"
    exit 1
fi

ip_address=$1
ping -c 5 "$ip_address"

